import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const target = resolve(root, 'src/client/generated/theme-assets.ts')
const sources = {
  warmCat: ['design/runtime/warm-cat.png', 'image/png'],
  moonlitGuardian: ['design/runtime/moonlit-guardian.png', 'image/png'],
  moonlitSleeper: ['design/runtime/moonlit-sleeper.png', 'image/png'],
  atelierTuxedo: ['design/runtime/atelier-tuxedo.png', 'image/png'],
  warmTexture: ['design/runtime/warm-paper-texture.webp', 'image/webp'],
  moonlitTexture: ['design/runtime/moonlit-paper-texture.webp', 'image/webp'],
  atelierTexture: ['design/runtime/atelier-paper-texture.webp', 'image/webp'],
}

const entries = await Promise.all(Object.entries(sources).map(async ([name, [file, mime]]) => {
  const buffer = await readFile(resolve(root, file))
  return [name, `data:${mime};base64,${buffer.toString('base64')}`]
}))
const output = [
  '/** Generated by scripts/embed-cat.mjs during build. */',
  `export const THEME_ASSETS = ${JSON.stringify(Object.fromEntries(entries))} as const`,
  '',
].join('\n')

await mkdir(dirname(target), { recursive: true })
await writeFile(target, output, 'utf8')
