import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const target = resolve(root, 'src/client/generated/theme-assets.ts')
const sources = {
  warmCat: ['design/runtime/warm-cat.png', 'image/png'],
  moonlitGuardian: ['design/runtime/moonlit-guardian.png', 'image/png'],
  moonlitSleeper: ['design/runtime/moonlit-sleeper.png', 'image/png'],
  atelierTuxedo: ['design/runtime/atelier-tuxedo.png', 'image/png'],
  warmTexture: ['design/runtime/warm-paper-texture.webp', 'image/webp'],
  moonlitTexture: ['design/runtime/moonlit-paper-texture.webp', 'image/webp'],
  atelierTexture: ['design/runtime/atelier-paper-texture.webp', 'image/webp'],
  warmCompanionResting: ['design/runtime/companion/warm-resting.webp', 'image/webp'],
  warmCompanionSleeping: ['design/runtime/companion/warm-sleeping.webp', 'image/webp'],
  warmCompanionStretching: ['design/runtime/companion/warm-stretching.webp', 'image/webp'],
  warmCompanionPlayingYarn: ['design/runtime/companion/warm-playing-yarn.webp', 'image/webp'],
  warmCompanionPetted: ['design/runtime/companion/warm-petted.webp', 'image/webp'],
  warmCompanionBed: ['design/runtime/companion/warm-bed.webp', 'image/webp'],
  moonlitCompanionResting: ['design/runtime/companion/moonlit-resting.webp', 'image/webp'],
  moonlitCompanionSleeping: ['design/runtime/companion/moonlit-sleeping.webp', 'image/webp'],
  moonlitCompanionStretching: ['design/runtime/companion/moonlit-stretching.webp', 'image/webp'],
  moonlitCompanionPlayingYarn: ['design/runtime/companion/moonlit-playing-yarn.webp', 'image/webp'],
  moonlitCompanionPetted: ['design/runtime/companion/moonlit-petted.webp', 'image/webp'],
  moonlitCompanionBed: ['design/runtime/companion/moonlit-bed.webp', 'image/webp'],
  moonlitLantern: ['design/runtime/companion/moonlit-lantern.webp', 'image/webp'],
  atelierCompanionResting: ['design/runtime/companion/atelier-resting.webp', 'image/webp'],
  atelierCompanionSleeping: ['design/runtime/companion/atelier-sleeping.webp', 'image/webp'],
  atelierCompanionStretching: ['design/runtime/companion/atelier-stretching.webp', 'image/webp'],
  atelierCompanionPlayingYarn: ['design/runtime/companion/atelier-playing-yarn.webp', 'image/webp'],
  atelierCompanionPetted: ['design/runtime/companion/atelier-petted.webp', 'image/webp'],
  atelierCompanionBed: ['design/runtime/companion/atelier-bed.webp', 'image/webp'],
  companionPurr: ['design/runtime/companion/cat-purr.wav', 'audio/wav'],
}

const entries = await Promise.all(Object.entries(sources).map(async ([name, [file, mime]]) => {
  const buffer = await readFile(resolve(root, file))
  return [name, `data:${mime};base64,${buffer.toString('base64')}`]
}))
const output = [
  '/** Generated by scripts/embed-cat.mjs during build. */',
  `export const THEME_ASSETS = ${JSON.stringify(Object.fromEntries(entries))} as const`,
  '',
].join('\n')

await mkdir(dirname(target), { recursive: true })
await writeFile(target, output, 'utf8')
